ORV2-2208 - FE: Send issued permit and permit payment receipt pdf via fax
bcgov/onroutebc pull request #1492
Opened 2024-07-17 23:48 UTC by glen-aot

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2024-07-18 00:38 UTC, zgong-gov approved these changes

2024-07-18 14:08 UTC, praju-aot requested changes

2024-07-18 14:08 UTC, praju-aot commented on frontend/src/features/idir/search/components/PermitResendDialog.tsx
> +            feature={FEATURE}
Kindly add formatting and validation similar to fax field in application page

2024-07-22 16:33 UTC, praju-aot approved these changes

2024-07-22 16:37 UTC, merged