Add LoA validation on pay now
bcgov/onroutebc pull request #1718
Opened 2024-12-23 21:15 UTC by gchauhan-aot

# Description

This PR is to add LoA validation on pay now. Verifies the consistency of loa data in database and permit snapshot. Validates permit type, dates and vehicles with  loa and loa snapshot data.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A: Manually tested in local using front end with correct data.
- [ ] Test B

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2024-12-27 15:02 UTC, praju-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +  async isValidLoa(permit: Permit): Promise<void> {
Can this be part of the validate endpoint?

2024-12-27 15:02 UTC, praju-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +  private validateLoaDetails(
Refactor to Loa helper or util or the loa module

2024-12-27 15:02 UTC, praju-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +  private validatePermitDataAgainstLoas(
Refactor to Loa helper or util or the loa module

2024-12-27 15:02 UTC, praju-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +    const loaNumbers = permitData.loas.map((loa) => loa.loaNumber);
Add optional chaining

2024-12-27 15:02 UTC, praju-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +    const { companyId } = permit.company;
Add optional chaining

2025-01-02 17:55 UTC, krishnan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +    dayjs(startDate).isSame(permitStartDate, 'day')
I think there's a function called `isSameOrBefore` in dayjs

2025-01-02 17:55 UTC, krishnan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +        dayjs(expiryDate).isSame(permitExpiryDate, 'day')
Similarly, `isSameOrAfter`

2025-01-02 17:55 UTC, krishnan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +  const permitData = JSON.parse(permit.permitData.permitData) as PermitData;
is this correct? `permit.permitData.permitData`, if so, can it not be flattened into one `permit.permitData`?

2025-01-02 17:55 UTC, krishnan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +      console.log('ReadLoADetails: ', readLoaDto);
Replace/remove `console.log`

2025-01-02 17:55 UTC, krishnan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +    validatePermitDataAgainstLoas(
What's the difference between these two functions? The both seemingly have the same set of checks on the same data.

2025-01-02 17:55 UTC, krishnan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> + * @returns {Promise<LoaDetail>} - Returns a Promise that resolves to the LOA detail.
Wrong comment block?

2025-01-02 17:55 UTC, krishnan-aot commented on vehicles/src/common/interface/permit.template.interface.ts
> +export interface Loas {
Does this change require following changes in FE?

2025-01-02 21:09 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +        dayjs(expiryDate).isSame(permitExpiryDate, 'day')
I could not find one, will check if isSameOrAfter works.

2025-01-02 21:09 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +    dayjs(startDate).isSame(permitStartDate, 'day')
I could not find one, will check if isSameOrBefore works.

2025-01-02 21:10 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +  const permitData = JSON.parse(permit.permitData.permitData) as PermitData;
This is correct. It is to access permitData json object under permitData table.

2025-01-02 21:10 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +      console.log('ReadLoADetails: ', readLoaDto);
sure.

2025-01-02 21:12 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +    validatePermitDataAgainstLoas(
first validates loa data from table against permit (ex permit type of permit and allowed permit types by LoA) and loa snapshot inside permit data against permit.

2025-01-02 21:15 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> + * @returns {Promise<LoaDetail>} - Returns a Promise that resolves to the LOA detail.
Can you help me understand what seems wrong in this comment block? there is a one thing that can be changed i.e. loa ID is actually loa number. I will do that.

2025-01-02 21:16 UTC, gchauhan-aot commented on vehicles/src/common/interface/permit.template.interface.ts
> +export interface Loas {
not really, I tested using frontend , BE is getting this data already.

2025-01-02 22:13 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +    dayjs(startDate).isSame(permitStartDate, 'day')
done.

2025-01-02 22:13 UTC, gchauhan-aot commented on vehicles/src/common/helper/validate-loa.helper.ts
> +        dayjs(expiryDate).isSame(permitExpiryDate, 'day')
done

2025-01-02 22:13 UTC, gchauhan-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +  async isValidLoa(permit: Permit): Promise<void> {
will do it in separate PR

2025-01-02 22:14 UTC, gchauhan-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +  private validateLoaDetails(
Done

2025-01-02 22:14 UTC, gchauhan-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +  private validatePermitDataAgainstLoas(
Done

2025-01-02 22:14 UTC, gchauhan-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +    const loaNumbers = permitData.loas.map((loa) => loa.loaNumber);
Done

2025-01-02 22:14 UTC, gchauhan-aot commented on vehicles/src/modules/permit-application-payment/payment/payment.service.ts
> +    const { companyId } = permit.company;
Done

2025-01-06 17:26 UTC, praju-aot requested changes

2025-01-06 17:26 UTC, praju-aot commented on vehicles/src/common/helper/permit-fee.helper.ts
> +export const findPermitHistory = async (
Why is function part of this file? Why not permit.services.ts

2025-01-06 17:26 UTC, praju-aot commented on vehicles/src/common/helper/permit-fee.helper.ts
> +  const specialAuth = await queryRunner.manager
Shouldn't this be part of special authorization module? Can we not import the module into permits or applications module if necessary as they are closely tied anyway

2025-01-06 17:26 UTC, praju-aot commented on vehicles/src/common/helper/permit-fee.helper.ts
> +    .from(Permit, 'permit')
It should be used as a last resort

2025-01-06 19:19 UTC, gchauhan-aot commented on vehicles/src/common/helper/permit-fee.helper.ts
> +export const findPermitHistory = async (
as discussed, it will introduce circular dependencies. duplicating in payment service for now. It will be removed after validation api is established.

2025-01-06 19:19 UTC, gchauhan-aot commented on vehicles/src/common/helper/permit-fee.helper.ts
> +  const specialAuth = await queryRunner.manager
After discussion, moved it to special auth api.

2025-01-06 19:20 UTC, gchauhan-aot commented on vehicles/src/common/helper/permit-fee.helper.ts
> +    .from(Permit, 'permit')
as discussed, it will introduce circular dependencies. duplicating in payment service for now. It will be removed after validation api is established.

2025-01-06 21:20 UTC, krishnan-aot approved these changes

2025-01-06 21:42 UTC, praju-aot approved these changes

2025-01-06 21:43 UTC, merged