chore(deps): override subdeps for semver vulnerability
bcgov/onroutebc pull request #775
Opened 2023-11-22 04:29 UTC by DerekRoberts

* https://github.com/bcgov/onroutebc/security/code-scanning/59
* https://github.com/bcgov/onroutebc/security/code-scanning/66

2023-11-27 23:25 UTC, cberg-aot commented
@DerekRoberts pr is failing now after merging with main.  not sure why

2023-11-28 23:57 UTC, krishnan-aot requested changes, later dismissed

2023-11-28 23:57 UTC, krishnan-aot commented on vehicles/package.json
> +    "@aws-sdk/s3-request-presigner": "^3.370.0",
These aws packages aren't used in vehicles. These have to be removed.

2023-11-29 00:17 UTC, DerekRoberts commented on vehicles/package.json
> +    "@aws-sdk/s3-request-presigner": "^3.370.0",
Thanks and corrected!  :)

2023-11-29 01:00 UTC, cberg-aot approved these changes

2023-11-29 18:00 UTC, merged